### ISSUE TITLE
Errors in platform responsiveness for Android

### ISSUE THREAD

**Issue by danbrown** [codedamn/core#1]
### Interface Error Report

On the courses tab, the courses icons are too tiny. And the topnav menu isn't good for mobile users experience. My sugestion is increase the courses block sizes and add a burger menu icon for navigation.

![WhatsApp Image 2020-03-22 at 2 05 45 PM (1)](https://user-images.githubusercontent.com/29470765/77255540-193b0e80-6c47-11ea-8378-ab539171afe4.jpeg)

Here on competitions tab, the title are too big for his container.

![WhatsApp Image 2020-03-22 at 2 05 45 PM](https://user-images.githubusercontent.com/29470765/77255521-032d4e00-6c47-11ea-8f1c-fcc2a54b3639.jpeg)

Edit: (I forgot about the specs)
### System information
Device: Xiaomi Redmi Note 7
Browser: Yandex Browser (based on Chromium)

**Comment by mehulmpt** [comment]
Thanks for reporting. Im labelling this as bug and would close the issue when the responsiveness for the dashboard is fixed.

**Comment by mehulmpt** [comment]
Hi! The responsiveness for the current site is fixed for the public-facing pages and the dashboard. Let me know if you're able to see any other problem with responsiveness on the mentioned pages for now.

**Comment by mehulmpt** [comment]
Should be fixed by now :D
