### ISSUE TITLE
Responsive Issue / Horizontal Scrollbar on Contact Page

### ISSUE THREAD

**Issue by AnirudhPanda** [codedamn/core#6]
![Capture](https://user-images.githubusercontent.com/66218496/129584997-ef5bd9c2-97fd-4acc-997a-1a4c601e39d5.PNG)

#### My Machine:

Resolution - 1366*768 Windows 10

**Comment by mehulmpt** [comment]
Thanks for reporting this Anirudh. Can you also share on what page it happens? Is it happening on every page?
