### ISSUE TITLE
Rather than entering the whole playground page just open the selected dev. environment

### ISSUE THREAD

**Issue by AnujSsStw** [codedamn/core#8]

**Comment by AnujSsStw** [comment]
like I hover on playground option and then select an option (it seems more natural to open up that selected playground rather than just redirecting to you in a new page)

![Screenshot (80)](https://user-images.githubusercontent.com/92370865/151616055-6c75c112-c0be-43e7-8da8-f4b4f3b5c86b.png)

When I click it should just open the Dev. environment (selected one) rather than opening the new page
 
![Screenshot (81)](https://user-images.githubusercontent.com/92370865/151616643-037a4b9f-a576-4ed8-a12d-d35e767ce45a.png)

**Comment by mehulmpt** [comment]
This should be fixed with our recent updates to playground pages
